<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="lenovo" name="Default test" tests="7" failures="1" timestamp="16 Apr 2016 07:22:10 GMT" time="0.284" errors="0">
  <testcase name="testDivideNumbers" time="0.049" classname="com.ga.helpers.math.MyMathTests"/>
  <testcase name="testPowerNumbers" time="0.015" classname="com.ga.helpers.math.MyMathTests"/>
  <testcase name="testPowerNumbers" time="0.014" classname="com.ga.helpers.math.MyMathTests"/>
  <testcase name="testPowerNumbers" time="0.006" classname="com.ga.helpers.math.MyMathTests"/>
  <testcase name="testPowerNumbers" time="0.016" classname="com.ga.helpers.math.MyMathTests"/>
  <testcase name="testPowerNumbers" time="0.006" classname="com.ga.helpers.math.MyMathTests"/>
  <testcase name="testPowerNumbers" time="0.011" classname="com.ga.helpers.math.MyMathTests">
    <failure type="java.lang.AssertionError" message="The result of 2 with power 2 is4 expected [2.8] but found [4.0]">
      <![CDATA[java.lang.AssertionError: The result of 2 with power 2 is4 expected [2.8] but found [4.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:207)
	at com.ga.helpers.math.MyMathTests.testPowerNumbers(MyMathTests.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- testPowerNumbers -->
</testsuite> <!-- Default test -->
